<?php
/**
 * initialize the supabase service class
 */
if (! function_exists('init_service')) {
    function init_service()
    {
        $service = new PHPSupabase\Service(
            config('supabase.api_config.api_key'),
            config('supabase.api_config.url')
        );

        return $service;
    }
}
/**
 * Setup supabase service
 */
if (! function_exists('setup_supabase')) {
    function setup_supabase()
    {
        try {

            //save service to session
            $service = init_service();
            session(['supabase_service' => $service]);

            //authenticate the user and save to session
            authenticate_user();
        } catch (Exception $ex) {
            return response()->json($ex->getMessage(), 500);
        }

    }
}
/**
 * return saved supabase instance in the session
 */
if (! function_exists('supabase_instance')) {
    function supabase_instance()
    {
        try {

           return  session()->get('supabase_service')->setBearerToken(session()->get('supabase_token'));
           
        } catch (Exception $ex) {
            return response()->json($ex->getMessage(), 500);
        }

    }
}
/**
 * authenticate a supabase user to allow RLS
 */
if (! function_exists('authenticate_user')) {
    function authenticate_user()
    {
        $service = init_service();
        $auth = $service->createAuth();
        $auth->signInWithEmailAndPassword(config('supabase.api_config.auth_email'), config('supabase.api_config.auth_password'));
        $data = $auth->data(); // get the returned data generated by request

        if (isset($data->access_token)) {
            session(['supabase_token' => $data->access_token]);
        }
    }
}
if (! function_exists('refresh_supabase_token')) {
    function refresh_supabase_token()
    {
        $bearerToken = session()->get('supabase_token');
        $service = init_service();

        //check the auth user
        $auth = $service->createAuth();
        $data = $auth->getUser($bearerToken);

        if (! isset($data)) {
            setup_supabase();
        }

    }
}
